### ISSUE TITLE
Dialog to Add Widget Not Working

### ISSUE THREAD

**Issue by remesq** [EtchUK/Etch.OrchardCore.AdminTheme#23]
![image](https://user-images.githubusercontent.com/727061/154855751-3746ea9f-ab4d-493b-abdc-8c3e461e37cd.png)

I'm not sure how to get the dialog to work, but clicking "Add" does nothing. No widget is added. Is there something I am missing?

I followed the directions to update the CT definitions with Category, Description and Icon. Not sure if there was something else I needed to do.

I added the Nuget package, not the source as a Project Reference.

Also, using OC 1.2.2, Microsoft Edge, VS 2022 CE, and IIS Express.

Any advice?

**Comment by peterkeating** [comment]
@remesq Suggest upgrading to the latest version 👍
