### ISSUE TITLE
It is abnormal after updating to Etch.OrchardCore.AdminTheme 1.8.0

### ISSUE THREAD

**Issue by effapp** [EtchUK/Etch.OrchardCore.AdminTheme#39]
It is abnormal after updating to Etch.OrchardCore.AdminTheme 1.8.0 , as follows:

![image](https://github.com/user-attachments/assets/5cd65f84-d43e-442b-b61a-7480602fb7be)

![image](https://github.com/user-attachments/assets/3135e2eb-6505-4049-a41c-470df106b8f5)

Bootstrap CSS didn't render.

**Comment by effapp** [comment]
An error occurred while rendering Header resource. System.InvalidOperationException: Could not find a resource of type 'stylesheet' named 'material-icons' with version '1'.

**Comment by effapp** [comment]
Hi @peterkeating,

An error occurred while rendering Header resource. System.InvalidOperationException: Could not find a resource of type 'stylesheet' named 'material-icons' with version '1'.

**Comment by effapp** [comment]
Hi @MylesB93, @peterkeating,
An error occurred while rendering Header resource. System.InvalidOperationException: Could not find a resource of type 'stylesheet' named 'material-icons' with version '1'.

**Comment by effapp** [comment]
Hi @Newnab,
How to fix this error,please?

**Comment by MylesB93** [comment]
Hi @effapp, this has now been fixed in the latest version
